### ISSUE TITLE
SUN600G3-EU-230 and SUN-MI-RELAY-0 with firmware MW3_16U_5406_2.27 stopped working

### ISSUE THREAD

**Issue by SMCerina** [kbialek/deye-inverter-mqtt#122] opened 2023-09-05 10:42 UTC
Hi,

after updating the firmware to 2.27 which is mandatory to use with the SUN-MI-RELAY-01 the logger status says offline. Even when I'm using modbux proxy for both connection to the inverter.

**Hardware (please complete the following information):**
 - Inverter model: Deye SUN600G3-EU-230

**Software (please complete the following information):**
 - Logger firmware version: MW3_16U_5406_2.27
 - deye-inverter-mqtt version: latest docker image on a Synology
 - config.env (remove passwords before pasting):

**Comment by kbialek** [comment] 2023-09-07 19:36
Very likely a duplicate of #123

**Comment by kbialek** [comment] 2023-09-13 13:42
Closing as duplicate of #123

**Closed by kbialek** 2023-09-13 13:42 UTC
Labels: duplicate, help wanted
